jobs:
  main:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Get Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./check/ci

name: Ci

on:
  schedule:
    - cron: "55 2/3 * * *"
